name: Bitrise
targets:
  Bitrise:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [Bitrise]
    info:
      path: ./Info.plist
      version: 0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
