//
// ActivityAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class ActivityAPI {
    /**
     Get list of Bitrise activity events
     
     - parameter next: (query) Slug of the first activity event in the response (optional)
     - parameter limit: (query) Max number of elements per page (default: 50) (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func activityList(next: String? = nil, limit: Int? = nil, apiResponseQueue: DispatchQueue = BitriseAPI.apiResponseQueue, completion: @escaping ((_ data: V0ActivityEventListResponseModel?,_ error: Error?) -> Void)) {
        activityListWithRequestBuilder(next: next, limit: limit).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get list of Bitrise activity events
     - GET /me/activities
     - List all the Bitrise activity events
     - API Key:
       - type: apiKey Authorization 
       - name: PersonalAccessToken
     - parameter next: (query) Slug of the first activity event in the response (optional)
     - parameter limit: (query) Max number of elements per page (default: 50) (optional)
     - returns: RequestBuilder<V0ActivityEventListResponseModel> 
     */
    open class func activityListWithRequestBuilder(next: String? = nil, limit: Int? = nil) -> RequestBuilder<V0ActivityEventListResponseModel> {
        let path = "/me/activities"
        let URLString = BitriseAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "next": next?.encodeToJSON(), 
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<V0ActivityEventListResponseModel>.Type = BitriseAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
