//
// AddonsSetupInstruction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AddonsSetupInstruction: Codable {

    public var cardContent: String?
    public var description: String?
    public var type: String?

    public init(cardContent: String? = nil, description: String? = nil, type: String? = nil) {
        self.cardContent = cardContent
        self.description = description
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case cardContent = "card_content"
        case description
        case type
    }

}

