//
// AddonsDeveloperLink.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AddonsDeveloperLink: Codable {

    public var title: String?
    public var url: String?

    public init(title: String? = nil, url: String? = nil) {
        self.title = title
        self.url = url
    }

}

