//
// AddonsFeature.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AddonsFeature: Codable {

    public var available: Bool?
    public var description: String?
    public var quantity: String?

    public init(available: Bool? = nil, description: String? = nil, quantity: String? = nil) {
        self.available = available
        self.description = description
        self.quantity = quantity
    }

}

