//
// AddonsSetupGuide.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AddonsSetupGuide: Codable {

    public var instructions: [AddonsSetupInstruction]?
    public var notification: String?

    public init(instructions: [AddonsSetupInstruction]? = nil, notification: String? = nil) {
        self.instructions = instructions
        self.notification = notification
    }

}

