//
// ServiceStandardErrorRespModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ServiceStandardErrorRespModel: Codable {

    public var message: String?

    public init(message: String? = nil) {
        self.message = message
    }

}

