//
// V0AddOnAppResponseItemModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AddOnAppResponseItemModel: Codable {

    public var icon: String?
    public var plan: AddonsPlan?
    public var planStartedAt: String?
    public var slug: String?
    public var title: String?

    public init(icon: String? = nil, plan: AddonsPlan? = nil, planStartedAt: String? = nil, slug: String? = nil, title: String? = nil) {
        self.icon = icon
        self.plan = plan
        self.planStartedAt = planStartedAt
        self.slug = slug
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case icon
        case plan
        case planStartedAt = "plan_started_at"
        case slug
        case title
    }

}

