//
// V0AddonsListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AddonsListResponseModel: Codable {

    public var data: [AddonsAddon]?

    public init(data: [AddonsAddon]? = nil) {
        self.data = data
    }

}

