//
// V0AndroidKeystoreFileUploadParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AndroidKeystoreFileUploadParams: Codable {

    public var alias: String
    public var password: String
    public var privateKeyPassword: String
    public var uploadFileName: String
    public var uploadFileSize: Int

    public init(alias: String, password: String, privateKeyPassword: String, uploadFileName: String, uploadFileSize: Int) {
        self.alias = alias
        self.password = password
        self.privateKeyPassword = privateKeyPassword
        self.uploadFileName = uploadFileName
        self.uploadFileSize = uploadFileSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case alias
        case password
        case privateKeyPassword = "private_key_password"
        case uploadFileName = "upload_file_name"
        case uploadFileSize = "upload_file_size"
    }

}

