//
// V0AppWebhookResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AppWebhookResponseModel: Codable {

    public var data: V0AppWebhookResponseItemModel?

    public init(data: V0AppWebhookResponseItemModel? = nil) {
        self.data = data
    }

}

