//
// V0AppListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AppListResponseModel: Codable {

    public var data: [V0AppResponseItemModel]?
    public var paging: V0PagingResponseModel?

    public init(data: [V0AppResponseItemModel]? = nil, paging: V0PagingResponseModel? = nil) {
        self.data = data
        self.paging = paging
    }

}

