//
// V0AppleAPICredentialsListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AppleAPICredentialsListResponse: Codable {

    public var data: [V0AppleAPICredentialResponseItem]?

    public init(data: [V0AppleAPICredentialResponseItem]? = nil) {
        self.data = data
    }

}

