//
// V0AppWebhookUpdateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AppWebhookUpdateParams: Codable {

    public var events: String
    public var headers: String?
    public var url: String

    public init(events: String, headers: String? = nil, url: String) {
        self.events = events
        self.headers = headers
        self.url = url
    }

}

