//
// V0AppWebhookResponseItemModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AppWebhookResponseItemModel: Codable {

    public var createdAt: String?
    public var events: [String]?
    public var headers: String?
    public var registeredByAddon: Bool?
    public var slug: String?
    public var updatedAt: String?
    public var url: String?

    public init(createdAt: String? = nil, events: [String]? = nil, headers: String? = nil, registeredByAddon: Bool? = nil, slug: String? = nil, updatedAt: String? = nil, url: String? = nil) {
        self.createdAt = createdAt
        self.events = events
        self.headers = headers
        self.registeredByAddon = registeredByAddon
        self.slug = slug
        self.updatedAt = updatedAt
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case createdAt = "created_at"
        case events
        case headers
        case registeredByAddon = "registered_by_addon"
        case slug
        case updatedAt = "updated_at"
        case url
    }

}

