//
// V0AppShowResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AppShowResponseModel: Codable {

    public var data: V0AppResponseItemModel?

    public init(data: V0AppResponseItemModel? = nil) {
        self.data = data
    }

}

