//
// V0AppAddOnsListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AppAddOnsListResponseModel: Codable {

    public var data: [V0AppAddOnResponseItemModel]?

    public init(data: [V0AppAddOnResponseItemModel]? = nil) {
        self.data = data
    }

}

