//
// V0ArtifactShowResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0ArtifactShowResponseModel: Codable {

    public var data: V0ArtifactResponseItemModel?

    public init(data: V0ArtifactResponseItemModel? = nil) {
        self.data = data
    }

}

