//
// V0AvatarPromoteResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0AvatarPromoteResponseModel: Codable {

    public var data: V0AvatarPromoteResponseItemModel?

    public init(data: V0AvatarPromoteResponseItemModel? = nil) {
        self.data = data
    }

}

