//
// V0BranchListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BranchListResponseModel: Codable {

    public var data: [String]?

    public init(data: [String]? = nil) {
        self.data = data
    }

}

