//
// V0BuildShowResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildShowResponseModel: Codable {

    public var data: V0BuildResponseItemModel?

    public init(data: V0BuildResponseItemModel? = nil) {
        self.data = data
    }

}

