//
// V0BuildWorkflowListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildWorkflowListResponseModel: Codable {

    public var data: [String]?

    public init(data: [String]? = nil) {
        self.data = data
    }

}

