//
// V0BuildRequestUpdateResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildRequestUpdateResponseModel: Codable {

    public var data: V0BuildRequestResponseItemModel?

    public init(data: V0BuildRequestResponseItemModel? = nil) {
        self.data = data
    }

}

