//
// V0BuildCertificateResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildCertificateResponseModel: Codable {

    public var data: V0BuildCertificateResponseItemModel?

    public init(data: V0BuildCertificateResponseItemModel? = nil) {
        self.data = data
    }

}

