//
// V0BuildCertificateListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildCertificateListResponseModel: Codable {

    public var data: [V0BuildCertificateResponseItemModel]?
    public var paging: V0PagingResponseModel?

    public init(data: [V0BuildCertificateResponseItemModel]? = nil, paging: V0PagingResponseModel? = nil) {
        self.data = data
        self.paging = paging
    }

}

