//
// V0BuildListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildListResponseModel: Codable {

    public var data: [V0BuildResponseItemModel]?
    public var paging: V0PagingResponseModel?

    public init(data: [V0BuildResponseItemModel]? = nil, paging: V0PagingResponseModel? = nil) {
        self.data = data
        self.paging = paging
    }

}

