//
// V0BuildLogInfoResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildLogInfoResponseModel: Codable {

    public var expiringRawLogUrl: String?
    public var generatedLogChunksNum: Int?
    public var isArchived: Bool?
    public var logChunks: [V0BuildLogChunkItemResponseModel]?
    public var timestamp: String?

    public init(expiringRawLogUrl: String? = nil, generatedLogChunksNum: Int? = nil, isArchived: Bool? = nil, logChunks: [V0BuildLogChunkItemResponseModel]? = nil, timestamp: String? = nil) {
        self.expiringRawLogUrl = expiringRawLogUrl
        self.generatedLogChunksNum = generatedLogChunksNum
        self.isArchived = isArchived
        self.logChunks = logChunks
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case expiringRawLogUrl = "expiring_raw_log_url"
        case generatedLogChunksNum = "generated_log_chunks_num"
        case isArchived = "is_archived"
        case logChunks = "log_chunks"
        case timestamp
    }

}

