//
// V0BuildLogChunkItemResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildLogChunkItemResponseModel: Codable {

    public var chunk: String?
    public var position: Int?

    public init(chunk: String? = nil, position: Int? = nil) {
        self.chunk = chunk
        self.position = position
    }

}

