//
// V0BuildRequestListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildRequestListResponseModel: Codable {

    public var data: [V0BuildRequestResponseItemModel]?

    public init(data: [V0BuildRequestResponseItemModel]? = nil) {
        self.data = data
    }

}

