//
// V0BuildListAllResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildListAllResponseModel: Codable {

    public var data: [V0BuildListAllResponseItemModel]?
    public var paging: V0PagingResponseModel?

    public init(data: [V0BuildListAllResponseItemModel]? = nil, paging: V0PagingResponseModel? = nil) {
        self.data = data
        self.paging = paging
    }

}

