//
// V0BuildCertificateUploadParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildCertificateUploadParams: Codable {

    public var uploadFileName: String
    public var uploadFileSize: Int

    public init(uploadFileName: String, uploadFileSize: Int) {
        self.uploadFileName = uploadFileName
        self.uploadFileSize = uploadFileSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case uploadFileName = "upload_file_name"
        case uploadFileSize = "upload_file_size"
    }

}

