//
// V0BuildTriggerParamsHookInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0BuildTriggerParamsHookInfo: Codable {

    /** Should be \&quot;bitrise\&quot; */
    public var type: String?

    public init(type: String? = nil) {
        self.type = type
    }

}

