//
// V0FindAvatarCandidateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0FindAvatarCandidateResponse: Codable {

    public var data: [V0FindAvatarCandidateResponseItem]?

    public init(data: [V0FindAvatarCandidateResponseItem]? = nil) {
        self.data = data
    }

}

