//
// V0OrganizationListRespModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0OrganizationListRespModel: Codable {

    public var data: [V0OrganizationDataModel]?

    public init(data: [V0OrganizationDataModel]? = nil) {
        self.data = data
    }

}

