//
// V0OwnerAddOnsListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0OwnerAddOnsListResponseModel: Codable {

    public var data: [V0OwnerAddOnResponseItemModel]?

    public init(data: [V0OwnerAddOnResponseItemModel]? = nil) {
        self.data = data
    }

}

