//
// V0OwnerAccountResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0OwnerAccountResponseModel: Codable {

    public var accountType: String?
    public var name: String?
    public var slug: String?

    public init(accountType: String? = nil, name: String? = nil, slug: String? = nil) {
        self.accountType = accountType
        self.name = name
        self.slug = slug
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case accountType = "account_type"
        case name
        case slug
    }

}

