//
// V0PlanDataModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0PlanDataModel: Codable {

    public var containerCount: Int?
    public var expiresAt: String?
    public var id: String?
    public var name: String?
    public var price: String?

    public init(containerCount: Int? = nil, expiresAt: String? = nil, id: String? = nil, name: String? = nil, price: String? = nil) {
        self.containerCount = containerCount
        self.expiresAt = expiresAt
        self.id = id
        self.name = name
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case containerCount = "container_count"
        case expiresAt = "expires_at"
        case id
        case name
        case price
    }

}

