//
// V0ProjectFileStorageResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0ProjectFileStorageResponseModel: Codable {

    public var data: V0ProjectFileStorageResponseItemModel?

    public init(data: V0ProjectFileStorageResponseItemModel? = nil) {
        self.data = data
    }

}

