//
// V0ProvisionProfileResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0ProvisionProfileResponseModel: Codable {

    public var data: V0ProvisionProfileResponseItemModel?

    public init(data: V0ProvisionProfileResponseItemModel? = nil) {
        self.data = data
    }

}

