//
// V0ProjectFileStorageDocumentUpdateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0ProjectFileStorageDocumentUpdateParams: Codable {

    public var exposedMetaDatastore: String?
    public var isExpose: Bool?
    public var isProtected: Bool?
    public var processed: Bool?
    public var userEnvKey: String?

    public init(exposedMetaDatastore: String? = nil, isExpose: Bool? = nil, isProtected: Bool? = nil, processed: Bool? = nil, userEnvKey: String? = nil) {
        self.exposedMetaDatastore = exposedMetaDatastore
        self.isExpose = isExpose
        self.isProtected = isProtected
        self.processed = processed
        self.userEnvKey = userEnvKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case exposedMetaDatastore = "exposed_meta_datastore"
        case isExpose = "is_expose"
        case isProtected = "is_protected"
        case processed
        case userEnvKey = "user_env_key"
    }

}

