//
// V0ProvProfileDocumentUpdateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0ProvProfileDocumentUpdateParams: Codable {

    public var isExpose: Bool?
    public var isProtected: Bool?
    public var processed: Bool?

    public init(isExpose: Bool? = nil, isProtected: Bool? = nil, processed: Bool? = nil) {
        self.isExpose = isExpose
        self.isProtected = isProtected
        self.processed = processed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case isExpose = "is_expose"
        case isProtected = "is_protected"
        case processed
    }

}

