//
// V0TestDeviceListResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0TestDeviceListResponseModel: Codable {

    public var data: [V0TestDeviceResponseItemModel]?

    public init(data: [V0TestDeviceResponseItemModel]? = nil) {
        self.data = data
    }

}

