//
// V0UserPlanRespModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0UserPlanRespModel: Codable {

    public var data: V0UserPlanDataModel?

    public init(data: V0UserPlanDataModel? = nil) {
        self.data = data
    }

}

