//
// V0UserProfileRespModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0UserProfileRespModel: Codable {

    public var data: V0UserProfileDataModel?

    public init(data: V0UserProfileDataModel? = nil) {
        self.data = data
    }

}

