//
// V0WebhookDeliveryItemShowResponseModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0WebhookDeliveryItemShowResponseModel: Codable {

    public var data: V0WebhookDeliveryItemResponseModel?

    public init(data: V0WebhookDeliveryItemResponseModel? = nil) {
        self.data = data
    }

}

