//
// V0WebhookRespModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct V0WebhookRespModel: Codable {

    public var status: String?

    public init(status: String? = nil) {
        self.status = status
    }

}

